### ISSUE TITLE
Missing definition of position angle (PA)

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#154]
I couldn't find the definition of position angle (PA).
Is it defined East-of-North like in galario ([docs](https://mtazzari.github.io/galario/py-api.html#galario.double.sampleImage)) so that PA=0 and inc=45deg would result in a vertical major axis and horizontal minor axis?

I think we should add this information in the docstrings of the functions using PA and also in the json parameter file helper.

**Comment by rbooth200** [comment]
I agree that it should be documented! 

The inc/PA are only used in the [deprojection](https://github.com/discsim/frank/blob/15b5ef3221320c9a24381fc73b37264aa5179de9/frank/geometry.py#L81), which are the same as [uvplot](https://github.com/mtazzari/uvplot/blob/9a03579d70bd99f862ab2a38c3e07521546f751e/uvplot/uvtable.py#L579). I'm sure you know best whether the uvplot / galario definitions are the same.

**Comment by jeffjennings** [comment]
That's right, it's east of north just as in uvplot. I don't follow why inc=45 deg would give a vertical major axis; inc=0 and PA=0 is face-on.

#155 addresses this by adding sign convention notation to `geometry.py` (in the header and description for `deproject`) and `parameter_descriptions.json`.

**Comment by jeffjennings** [comment]
I think #155 resolved this, but @mtazzari let me know if you think there's still more to address.

**Comment by mtazzari** [comment]
Oh sure, I thought it was linked to the PR. Closing.
