### ISSUE TITLE
circleci tests queuing 

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#156]
The circleci tests for any given push are still constantly failing because the tests are being queued (not running) with the notice, "This job was waitlisted due to your concurrency limits". The tests are delayed from starting by 5 - 9 minutes, then time out at ~10 minutes and so 'fail'. You have to re-run tests multiple times to get all of them to pass, which can take 30 minutes - > 1 hr for a single push.

The circleci account plan says we can have "1 concurrent job with access to Linux and Windows builds on Small and Medium sizes". 

I googled and don't know why this queuing started happening seemingly randomly. I found this -  https://support.circleci.com/hc/en-us/articles/360055741771-Build-Not-Running-due-to-concurrency-limit-but-no-other-job-is-running - but I don't see any background jobs that are running which would cause the tests to queue.

Unless someone sees a quick fix, we should open a support ticket on circleci.

**Comment by mtazzari** [comment]
Hey, I was just about to open an issue to migrate to Github Actions. I just did it for both uvplot and galario. It's just great, tests are run immediately and it's completely free for public projects.
I'll open an issue asap.

**Comment by mtazzari** [comment]
Opened issue #157

**Comment by jeffjennings** [comment]
Awesome, thank you! Sounds much faster and easier

**Comment by mtazzari** [comment]
I'll have a look in the next days and will submit a PR.
