### ISSUE TITLE
Unclear behaviour for fixed input geometry

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#159]
If a user sets, let's say, inclination and/or P.A., by setting their values in the `parameters.json`:
```json
  "geometry" : {
    "type"             : "gaussian",
    "fit_phase_offset" : false,  # default: true
    "fit_inc_pa"       : false,      # default: true
    "initial_guess"    : false,  
    "inc"              : 29.0,          # default: 0.0
    "pa"               : 90.0,          # default: 0.0
    "dra"              : 0.0,
    "ddec"             : 0.0
  },
```
and does not change `"type"` to `"known"`, then frank still fits for the geometry but does not use the provided `inc` and `pa`. 
I find this confusing. I believe this is also undocumented, probably because it is not the desired behaviour.

I propose a solution: if `initial_guess` is false and one of the four geometry parameters are *not* 0.0, then frank checks that `type` is set to known or raises an Error.

**Comment by jeffjennings** [comment]
Hey Marco, 

Thanks for this. Are you using the version of `frank` from pip? The current version of master has corrected this by applying the supplied dra/ddec if `fit_phase_offset` is true and/or applying the supplied inc/pa if `fit_inc_pa` is `true`, regardless of the value of `type` (see the block beginning [here](https://github.com/discsim/frank/blob/9464c1fb257b121f59cb33e65926076a07cc72f1/frank/fit.py#L302)). 

The type of geometry being applied/fitted for is also printed to the terminal at runtime, including this caveat in the current version of master -- "You requested a Gaussian fit to determine the geometry, but you provided values for inclination, PA, and the phase offset. --> Using your provided values (not fitting for the geometry)".

**Comment by jeffjennings** [comment]
(This is also why we have the `fit_phase_offset` and `fit_inc_pa` arguments in the .json.)

**Comment by jeffjennings** [comment]
Yeah sorry for the bug! I'll open PRs for the last minor things I have this week that I'd like to include in the 1.1.0 release, then finally push that to PyPI.

Awesome re:#157, that would be super helpful!

**Comment by jeffjennings** [comment]
I've verified the input geometry is handled as expected, so going to close this!
