### ISSUE TITLE
storing priors in 'sol'

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#165]
Hey @rbooth200 I think I remember we talked about this before, but could we could store the 5 hyperparameters in `sol` as a dictionary (say, `priors` or similar)? When loading a `sol.obj` saved from a fit, the filename currently includes alpha and wsmooth, but it would be helpful if those were stored in the object so the fit would be more easily reproducible.

**Comment by rbooth200** [comment]
That's a good idea. To be flexible I'd probably add an optional "info" dictionary to the sol object. You can store alpha, etc, plus its easily adaptable to add other notes at a later date

**Comment by jeffjennings** [comment]
that sounds good; I would think the best point to add this would be in `FrankFitter`, in the `__init__`, as this takes in all the hyperparameters. Sound good, or do you think it should be deeper, like in `FrankGaussianFit` and `FrankLogNormalFit`?

**Comment by rbooth200** [comment]
I think your only storing the sol object, not the fitter so this would need to be deeper. I would probably make `FrankRadialFit` store the info object, with it being passed through the constructors of `FrankGaussianFit` and `FrankLogNormalFit`, in a similar way to the DHT or geometry.

**Comment by jeffjennings** [comment]
ok I did this in c49fc18 in the lognormal branch; let me know / feel free to change if you think it should be done differently. but that PR will close this issue.

**Comment by rbooth200** [comment]
Looks good, see the comment I made on the PR
