### ISSUE TITLE
Copyright notice for interactive usage

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#17]
Consider adding this when starting frankenstein, as suggested by the GPL instructions:

```
    Frankenstein  Copyright (C) 2019-2020  R. Booth, J. Jennings, M. Tazzari
    This program comes with ABSOLUTELY NO WARRANTY; for details type <<<>>>.
    This is free software, and you are welcome to redistribute it
    under certain conditions; see the full LICENSE attached to this package.
```

**Comment by jeffjennings** [comment]
I think it's a bit overkill to print this whenever running the code; it's good to keep the print statements as lean as possible, especially as it's easy to run the code several times in succession in say a few minutes.
