### ISSUE TITLE
Predict using a different geometry

### ISSUE THREAD

**Issue by anibalsierram** [discsim/frank#172]
Hi! I think that there is a small error when trying to predict the visibilities using a different geometry.

Right now the code is:
```
 if geometry is not None:
        u, v = self._geometry.deproject(u, v)
```
but I think that the correct one should be:

```
 if geometry is not None:
        u, v = geometry.deproject(u, v)

```

Thanks!!

**Comment by rbooth200** [comment]
Hi @anibalsierram

Thanks! I agree this a bug, we will fix it ASAP.
