### ISSUE TITLE
Review tutorial

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#20]
Make sure the tutorial is final and polished.

**Comment by jeffjennings** [comment]
The tutorials are on my branch _docs_and_runner_jj_. I suggest closing this issue once you've looked through them.

**Comment by rbooth200** [comment]
Open a PR

**Comment by jeffjennings** [comment]
I don't think this needs to be left open as an issue; we'll all need to look through the docs, including the tutorials, when they're final. I'm closing.
