### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by rbooth200** [discsim/frank#21]
It would be useful to have some output to tell users what the code is doing. E.g. when the geometry is being fit, what kind of model is being fit to the data, important parameters used etc.

**Comment by jeffjennings** [comment]
I've now added this to `docs_and_runner_jj` in #35. If it looks good, close this out!

**Comment by jeffjennings** [comment]
#35 now uses the `logging` module to both print the above (my last message) to terminal during runtime and to write to `frank_fit.log`.

Ready to close!
