### ISSUE TITLE
wrong syntax for np.atleast_1d ?

### ISSUE THREAD

**Issue by edstevenson** [discsim/frank#210]
line 426 of utilities.py

`np.atleast_1d(wle, dtype='f8')` raises TypeError

should maybe be `np.atleast_1d(wle).astype('f8')` ?

**Comment by rbooth200** [comment]
Can you provide a minimum example that reproduces the error?

**Comment by jeffjennings** [comment]
This is due to an update to the numpy core; the `dtype` arg is no longer accepted by `np.atleast_1d` as of some recent version (my version of numpy, 1.21.5, returns the error). 

I've fixed in #212 and confirmed the `dtype` arg to `atleast_<x>d' isn't elsewhere in frank.

Thanks @edstevenson!
