### ISSUE TITLE
Warning about bad power spectrum

### ISSUE THREAD

**Issue by j6626** [discsim/frank#218]
I was getting the following warning for certain choices of parameters: "Bad value in power spectrum. The power spectrum must be positive and not contain any NaN values. This is likely due to your UVtable (incorrect units or weights), or the deprojection being applied (incorrect geometry and/or phase center). Else you may want to increase `rout` by 10-20% or `n` so that it is large, >~300." In my case, I found that _decreasing_ rather than increasing r_out fixed things, so it may be helpful to users to make the warning more general.

**Comment by jeffjennings** [comment]
Hi @j6626, I'm sorry to only be seeing this now, but I've made #221 to address it. Thank you for letting us know!
