### ISSUE TITLE
Determining weights of mock data

### ISSUE THREAD

**Issue by rbooth200** [discsim/frank#22]
CASA simulations for ALMA do not have a good estimate of the weights. Should we include our utility routine that we use for that?

**Comment by jeffjennings** [comment]
The histogram routine has worked well for the several mock discs I've tested. We could include this in `frank/useful_functions.py` so it's outside the main code and just call this function to update the weights in-between loading the data and calling a geometry class. 

I could then put together a super short tutorial for the docs on fitting mock data. 

@mtazzari, is this a common enough problem for people (mock data needing the weights to be determined before fitting the visibilities) that it's worth including?

**Comment by mtazzari** [comment]
Yes, this would definitely be a useful utility to have handy.
It's not urgent though -- it can be done after paper acceptance.

**Comment by rbooth200** [comment]
I believe this was fixed in #73
