### ISSUE TITLE
Uncertainty on log normal fits

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#220]
For a few sources (faint debris disks over a range of inclinations), I've found that the uncertainty on log normal fits as computed by [`get_fit_stat_uncer`](https://github.com/discsim/frank/blob/535c63a77c3595c2e3f7be9ad64182fad0737335/frank/utilities.py#L141) can start to blow up and go negative near r=0. This can be somewhat but not always alleviated by adjusting fit parameters including alpha, wsmooth and rout. @rbooth200 , any ideas on how to fix? 

A couple examples:
![ex1](https://github.com/user-attachments/assets/437dece0-1674-46f8-9a9f-85ca22dd0291)
![ex2](https://github.com/user-attachments/assets/19443e36-1f14-4d18-9e2b-88e8fd612e2d)

**Comment by rbooth200** [comment]
Would you be happy plotting `exp(mu +/- sig_mu)` where `sig_mu` is the variance of `log(I)` and `mu` is the mean of `log(I)` instead of `exp(mu) +/- sig_I` where `sig_I` is the variance of `I`? The former seems sensible for a log-normal model.

**Comment by jeffjennings** [comment]
Ah ok, yes I just tried that and it works well, thank you! I'll open a PR to give the option to return the log standard deviation.
