### ISSUE TITLE
Some reading confusion in radial_fitters

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#39]
@rbooth200 

https://github.com/discsim/frank/blob/72b249954c2946873e56548b45744a0bef490dd8/frank/radial_fitters.py#L414

If I'm reading this right, for `q` in this line and `V` in the line above it, you're using these variables to denote the observed baselines and observed Re(V). But (I think) everywhere else `q` is the spatial frequency collocation points and `V` the visibility amplitudes at `q`. 

Can you change `q` here and anywhere else I'm missing to `bls` or something distinct to denote where it's the observed baselines, and change `V` here and anywhere else I'm missing to `vis` (as it is in `geometry.py`) to denote where it's the observed visibilities?

**Comment by rbooth200** [comment]
I don't agree with this, we explicitly use V(q) in the paper, so I would prefer to keep the current notation. It makes even more sense when you think about the arguments passed to the DHT - these should be spatial frequencies. hence q is the correct notation. 

If anything we should change vis-> V in geometry. OK?

**Comment by rbooth200** [comment]
I've pushed a commit doing this to docs_and_runner_jj

**Comment by jeffjennings** [comment]
I agree it's good to be consistent throughout the code. I just find it a bit confusing that a single variable `q` (or `V`),  refers in different parts of the code to either the data or the model. And that the variable in those 2 cases is (or is at for `V`) different baselines. If you don't think that's confusing, I think at least some inline commenting would be helpful.

**Comment by rbooth200** [comment]
capital V (visibilities) and lower-case v (one component of the uv-points) are now used consistently throughout the code so no comments are needed here. I also don't see what the problem is with q either. The definition is consistent with the paper and the rest of the code.

**Comment by jeffjennings** [comment]
After discussing, we've agreed. Closing!
