### ISSUE TITLE
add plotting functions to API

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#45]
Per MT's suggestion

**Comment by mtazzari** [comment]
I'd add just a section "Plotting functions" with a reference to the `make_figs.py` and `plots.py` modules.
I set "Paper resubmitted as deadline", because I think it will take 5 minutes. If you think it'll take more, then move it to "Paper accepted & on arXiv"

**Comment by jeffjennings** [comment]
Closing: now included in PR #55
