### ISSUE TITLE
Test the whole pipeline inc. figures and data

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#48]
See discussion in #7 

For the full pipeline test, there are already tests for the geometry fitting and the brightness profile fitting.
What's missing is a test for the full pipeline, as it would additionally be testing that figures and data files can be generated (that np.genfromtxt and plt.savefig are working).

**Comment by jeffjennings** [comment]
- [ ] Also add test for the all geometry options, e.g., supplying a fixed geometry (I'm getting an error in `radial_fitters.fit` with a supplied geometry).

**Comment by rbooth200** [comment]
To make the unit tests run quickly here it's worth doing what we do for the other tests:

- fit a subset of the data 
- fit only a few bins 
- write the output to /tmp

**Comment by rbooth200** [comment]
I think is now fixed - we actually have full pipeline fits in master.
