### ISSUE TITLE
RuntimeWarning in BinUVData

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#53]
Traceback: 

```
/Users/morgan/miniconda3/envs/jj/lib/python3.7/site-packages/frank/useful_funcs.py:117: RuntimeWarning: invalid value encountered in sqrt
  bin_vis_err.real = np.sqrt(bin_vis_err.real - bin_vis.real**2)
```

**Comment by rbooth200** [comment]
Can you give me a minimum example to reproduce this?

**Comment by jeffjennings** [comment]
Run the code on any branch, the binning gets called so long as the figures are made.

**Comment by rbooth200** [comment]
I don't get this error on master branch if I save your file as tmp.json and run it as follows:
python -m frank.fit -p tmp.json -uv tutorials/AS209_continuum.npz

**Comment by jeffjennings** [comment]
Ok once my branch is merged I'll check on master. I've seen the error on my previous branch too, so not sure why it's not showing on master.

**Comment by rbooth200** [comment]
I'll dig a bit

**Comment by rbooth200** [comment]
Sorry, wrong issue
