### ISSUE TITLE
Decide where to store binary files

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#6]
Where should we store large binary files e.g. .npz, .dat etc?
They are useful to carry out examples or tests, but they increase the repo size considerably.
Idea:
 - store in another repo, e.g. discsim/data and download it whenever one wants to use it. 
 - store in zenodo

**Comment by jeffjennings** [comment]
I think the best solution is just to store them in the _docs_ directory of the frank repo. Having a Manifest.in in the repo (on 1 of my branches, will submit pull request soon -- see https://packaging.python.org/guides/using-manifest-in/) allows us to exclude specific files and/or directories, like _docs_, from the pip package.

**Comment by rbooth200** [comment]
docs is surely the wrong place for them. Is it possible to have "data" folder and exclude that?

**Comment by jeffjennings** [comment]
Hmm as these data are only used for the quickstart and tutorials, and those are part of the docs, I think it makes the most sense to have these data within "docs". We can have a folder in docs that's "example_data", but I think if there's a "data" folder outside docs, it's confusing when looking at the repo what data this is. It's also kind of a headache referencing files in the tutorial .ipynb notebooks that are outside the docs directory.

**Comment by jeffjennings** [comment]
I think we've agreed on storing big files in the _tutorials_ folder, so I'm closing this.
