### ISSUE TITLE
Add logging to additional scripts

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#60]
To track fit iteration real-time and the slower saving operations (saving UVTables)

**Comment by rbooth200** [comment]
Quick Q: Why is saving the UVTables slow? It would probably be must faster to save them in .npz format. Can we do that as default?

**Comment by jeffjennings** [comment]
Slow because they can be >100 MB, like for as209.

I think it would be best to strip the file extension from the input uvtable
(that's currently just allowed as .dat, .txt, .npy, .noz) and save to the
same format.

If people aren't using CASA inside Python and we save to .npz as default,
they'd have to reformat the saved tables, so want to avoid that.

**Comment by rbooth200** [comment]
That's acutally not true. The default version of CASA comes with numpy. Its an ancient version, but it supports npz files.

**Comment by jeffjennings** [comment]
The point stands, it should be the same format as the input filename.

**Comment by rbooth200** [comment]
Ok, that's fair. It's not the current behaviour though - I'll open a PR

**Comment by jeffjennings** [comment]
Closing: deprecated. See #71
