### ISSUE TITLE
Option to run frank just to produce UVTables

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#66]
An additional option to just generate the uv tables without refitting (even though in most cases the fitting will be very fast). Add the call syntax and function for it.
`python -m frank.fit -uv uvtable --generate_uvtables sol.obj`
would be good.

**Comment by jeffjennings** [comment]
Looking at this again, I don't think this functionality is that useful. You'd have to pass in a sol.obj _and_ the original datafile that was fit (in order to get the u and v coordinates that sol.predict needs). Fits are so fast that it seems less error prone to just re-run a fit if you need frank UVTables. I suggest we close this.

**Comment by rbooth200** [comment]
I thought the whole point was that the UV table could be different?

**Comment by jeffjennings** [comment]
Ah I thought you just wanted to make the same tables you'd get from the original fit. Ok, still I think this is prone to error and that it'd just be better to rerun a fit on a given input uvtable to get the corresponding frank uvtables.

**Comment by rbooth200** [comment]
Ok, let's leave it for now, but don't close the issue. I'll provide an
implementation in the future if needed.

**Comment by jeffjennings** [comment]
Can you remind me what you had in mind for this exactly? Was it to take a `sol` object from a previous fit and apply it to a new UVTable of observations to produce corresponding frank UVTables? If so, I think it's safer to just re-run an entire fit using the new UVTable.

**Comment by rbooth200** [comment]
> Was it to take a sol object from a previous fit and apply it to a new UVTable of observations to produce corresponding frank UVTables?

Yes, but the use case I had in mind was to make it possible to use the code to make predictions, e.g. if you've got observations in Band 7 and you wanted to make predicted images etc for Band 3, maybe at lower resolution then you'd need to be able to fit one dataset and predict the vis for a different one. 

This can be done using the library interface easily enough though

**Comment by jeffjennings** [comment]
Ok cool I see, I'd suggest we close this then and if needed, make a small tutorial showing how to predict visibilities at some given set of baselines given a fit at another set. I'm somewhat skeptical of how well frank could predict a fit in one band given a fit in another band; the data's noise properties will be different, so I could imagine one could easily get a fit that either goes too far or not far enough into noisy longer baselines. I think it's safer to just mock up the new band or configuration data and do a new fit to 'predict.' 

But I haven't tested this myself, so if you think it's useful, it could be a tutorial.

**Comment by rbooth200** [comment]
I'm happy to close this -- we can leave writing the tutorial until the point that someone asks.

**Comment by jeffjennings** [comment]
Cool, thanks!
