### ISSUE TITLE
Update logging in fit.py to inform the user UVTables will be saved

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#68]
And that these will be of comparable size to the input UVTable

**Comment by jeffjennings** [comment]
Closing: this should've been closed by PR #73, but I had a typo

**Comment by rbooth200** [comment]
Is that true? Didn't we remove the logging from that PR?

**Comment by jeffjennings** [comment]
The logging is no longer in fit.py, but in the version of io.py I've opened in PR #76 . I think it easiest to leave this closed as it's deprecated and point logging things to #71.
