### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mtazzari** [discsim/frank#7]
We would need to add a few tests, at least:
 - to test the package can be imported
 - to test the objects can be initialised correctly

Ideally:
 - to test that Frank produces the same result on the same dataset (perhaps fixing the random seed we can obtain reproducible results to a numerical precision level?)
 
These tests would be run automatically after any push command.

**Comment by jeffjennings** [comment]
For the IO test, in `tests.py` there's 
```
def test_import_data():
    # TODO
    pass
```
but how useful is this, as it'll just be checking that `np.genfromtxt` and `np.savetxt` / `np.save` are working? 

For the full pipeline test, there are already tests for the geometry fitting and the brightness profile fitting; is there utility in a test for the full pipeline, as it would just additionally be testing that figures can be generated (that `np.genfromtxt` and `plt.savefig` are working)?

**Comment by mtazzari** [comment]
Regarding the IO test, now there is a meaningful test [here](https://github.com/discsim/frank/blob/a8a1221448ab0b2f1e904c7827f92f3478e94ca0/frank/tests.py#L90)
```
def test_import_data():
    """Check the UVTable import function works for a .txt"""
    load_uvtable('tutorials/test_datafile.txt')
```

**Comment by mtazzari** [comment]
Regarding the full pipeline test, I agree it would be nice to have it -- indeed I added that in Dec to the todo list above.
However to implement such text will require non-trivial amount of work to check files are created, populated correctly, etc. It could easily take a few days of work.
I've opened #48 to track this.
