### ISSUE TITLE
logging in radial_fitters to give running count of iteration number

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#72]

**Comment by rbooth200** [comment]
I'm happy to have this in general, but I suspect that it will be difficult to provide a correct implementation. No implementation is better than a bad one.

Have you thought about how to do this in a way that will work for both the command line and the log files?

**Comment by jeffjennings** [comment]
Yes the version on my branch `vis_histogram` works by printing the real-time iteration to the terminal only, and printing the final number of iterations to the single log file.

**Comment by jeffjennings** [comment]
Closing: this should've been closed by PR #73, but I had a typo
