### ISSUE TITLE
put package on pypi

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#81]

**Comment by rbooth200** [comment]
If we're happy not shipping the AS209 data set, tutorials and docs (which I think is correct), then I think everything for this in ready to go when we are.

**Comment by mtazzari** [comment]
I also think it's correct not to ship the AS209 data, tutorials and doc with the PyPI package.
I'd try to publish to PyPI before we release 1.0.0 to avoid to mess up the PyPI repository.

**Comment by rbooth200** [comment]
I assume Jeff needs to do this as he is owner of the PyPI repo.

**Comment by mtazzari** [comment]
here there is a quick wiki I've written to do that: https://github.com/mtazzari/uvplot/wiki/How-to-upload-a-new-version-to-PyPI

If useful, we can copy & adapt the wiki for frank.
It will come the day in which we won't remember how we did it..
So, in any case, I suggest we have a wiki page in discsim/frank that explains how to publish a new version to pypi.

I think for now it's best if Jeff does it, then we can find whether maintainers etc can be designated to ensure continuity. 
Even better (for later) we should implement this in circleCI. A `publish-to-PyPI` job that is done only for master branch commits tagged with a `vx.y.z` tag.

**Comment by rbooth200** [comment]
Great, I added a [wiki page](https://github.com/discsim/frank/wiki/How-to-upload-a-new-version-to-PyPI) enabling that. Is there anything we need to add to setup.py?

**Comment by jeffjennings** [comment]
Hey @rbooth200 and @mtazzari, I added Marco as an owner to the PyPI `frank` "project"; Richard can you make an account on PyPI and let me know your username so I can add you too? Thanks!

**Comment by rbooth200** [comment]
I created a PYPi using rbooth200 as the username.
