### ISSUE TITLE
scrub multiple copies of large UVTables from repo to reduce its size

### ISSUE THREAD

**Issue by jeffjennings** [discsim/frank#84]
How-to: https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

The repo size is currently ~90 MB (see https://api.github.com/repos/discsim/frank --> "size" (in kB)). It can be reduced if we delete redundant copies of the AS 209 dataset from the repo's history. 

I'd like to keep one copy of the dataset though so that someone can reproduce the exact results shown with it in the tutorial notebooks.

- [ ] Also check that the size of the pypi package is small

**Comment by rbooth200** [comment]
This can be done (best using bfg). But will it really make much difference? 100 Mb is not terribly large.

**Comment by jeffjennings** [comment]
Richard noted he checked that removing duplicate copies of the AS 209 UVTable makes a trivial difference to the repo's total size, so I'm closing this.
