### ISSUE TITLE
Real and Img error calculation

### ISSUE THREAD

**Issue by bjnorfolk** [discsim/frank#89]
Hi,

I'm attempting to use Frank for fitting radial brightness profiles and visibility curves. I've used the code to fit the visibility curve of HD100453 and I believe there's an error in the error calculation for the real and imaginary components, as you can see in my plot the ALMA obs (triangles) have unusually large errors initially and the ATCA obs (squares) have insignificant errors. 
![image](https://user-images.githubusercontent.com/34231154/77596861-44787300-6f51-11ea-9f74-e48f7c834625.png)

I'm normalising the curve by the model, and error calc code is as follows (I believe I've followed the tutorial correctly):
```python
vis_err_re_kl_alma = (binned_vis_alma.error.real/sol_alma.predict_deprojected(grid_alma).real[0])
vis_err_img_kl_alma = (binned_vis_alma.error.imag/sol_alma.predict_deprojected(grid_alma).real[0])
```
I believe the error originates in the utilities.py script in UVBinner line 101
```python
bin_vis_err.real += np.bincount(idx, weights=tmp_wgt*tmp_vis.real**2, minlength=nbins)
```
Shouldn't the weights be tmp_wgt*(tmp_vis.real**2 minus some average ie mean, std) ?

**Comment by rbooth200** [comment]
Hi Brodie,

You're correct in thinking that the line you highlighted is computing an average of V^2 rather than the variance. The variance is computed below that line (see [here](https://github.com/discsim/frank/blob/057bf7f0ac7e49fc80771a8396384da07660d8c2/frank/utilities.py#L121)). 

Are you using the geometry determined by frank? If so, then the error could be large since that geometry is a poor fit. A bad estimate of the geometry means the de-projection is done poorly and each uv bin will contain a mixture of visibilities from a range of different scales. This will cause the variance (and hence error estimate) to go up.

**Comment by bjnorfolk** [comment]
When you say geometry do you mean the inc and PA? Am I able to input these values instead of letting Frank determine them?

**Comment by rbooth200** [comment]
Yes, inc, PA (+ the phase centre, if needed). How are you using frank?

**Comment by bjnorfolk** [comment]
I'm following the "Performing a fit using frank as a Python module", but I can see in the terminal section that there's a parameter file. I assume I would alter the inc and PA entries? But is there a way to do this while using Frank as a python module?

**Comment by rbooth200** [comment]
That's fine - have a look in the geometry.py file, there is class called FixedGeometry you can use that with the published geometry instead of  FitGeometryGaussian

**Comment by bjnorfolk** [comment]
Thanks Robert, that was precisely what I was looking for. The curve now matches my own vis curve:
![image](https://user-images.githubusercontent.com/34231154/77639555-0f017300-6fad-11ea-8208-c1784b730cf4.png)
But the think I'm either calculating the errors incorrectly or I'm using Frank incorrectly for the errors.
The blue and red circles are produced from my own vis code and I believe the errors make much more sense since they are significant and increasing for my ATCA data, and insignificant for my ALMA data. I calculated the errors using
```python
np.std(real_values[binwidth])/np.sqrt(len(binwidth[0]))
```
Is there a way to use Frank to calculate the standard deviation of the real and imaginary values for the errors?

**Comment by rbooth200** [comment]
What happens if you pass an array of 1's for the weights into the UV binner in frank? That *should* give you an unweighted standard deviation, similar to your calculation.

**Comment by bjnorfolk** [comment]
If I set the weights to an array of ones:
```python
weights_atca=np.ones(len(u_atca))
```
I think it bugs the code majorly.
![image](https://user-images.githubusercontent.com/34231154/77643892-3e67ae00-6fb4-11ea-9f01-96e8b88a3c93.png)

**Comment by rbooth200** [comment]
I expected the fits to be wrong, so I'm not worried about that. I think I've gotten to the bottom of the issue, which is the what I've called the error is the sample variance in each bin rather than the uncertainty on the mean. I'll push a fix to a branch. Give me a few mins...

**Comment by rbooth200** [comment]
Can you see whether the new error calculation, as done in the "error" branch provides a better estimate?

**Comment by rbooth200** [comment]
Actually, hold on a minute

**Comment by rbooth200** [comment]
Ok, it should now be correct

**Comment by rbooth200** [comment]
Ok, so I've made a few changes and done some tests, the new estimate should be working. Can you confirm?

**Comment by bjnorfolk** [comment]
Sorry Robert, I think we are in slightly different time zones. In Melbourne it was getting very late.

I've cloned your error branch and I believe the issue is fixed, here's the results:
![image](https://user-images.githubusercontent.com/34231154/77697169-75fd4700-7002-11ea-8c30-6bb7870f39fa.png)
The error bars look much more believable.
