### ISSUE TITLE
Binning and averaging the data

### ISSUE THREAD

**Issue by bjnorfolk** [discsim/frank#91]
Hi again,

Last one I promise. 

I've been looking through the utilities.py code and I'm not really sure why you're multiplying the uv data by the weights? i.e. line 94
```python
bin_uv += np.bincount(idx, weights=tmp_wgt*tmp_uv, minlength=nbins)
```
From my understanding this should only be applied to the real and imaginary components?
Cheers,
Brodie

**Comment by rbooth200** [comment]
Hi Brodie, 

This is the weighted average of the baseline, in much the same way that we compute the weighted average of the visibility. This is just some sensible estimate for the typical baseline length in a given bin. One could use the bin centre of unweighted mean instead. If you think about it, the weighted average makes more sense though. Imaging a case where the bin just has two uv points, one with high weight, one with low weight. It makes sense that the estimate of the uv point as well as the visibility amplitude should both be dominated by the one with the high weight.

**Comment by rbooth200** [comment]
I believe this is also resolved, closing
