### ISSUE TITLE
Over-fitting and negative flux

### ISSUE THREAD

**Issue by bjnorfolk** [discsim/frank#95]
Hi again,

I've been using Frank to fit a sample of 16 transition disks and for all I can a negative flux for my ATCA and ALMA observations, and over-fitting. Here's the vis curve and radial brightness profile for HD163296.
![image](https://user-images.githubusercontent.com/34231154/78216212-0a850f00-7505-11ea-830f-dc7aa03766f8.png)

I was wondering if:
1. Frank had a prior to prevent negative fluxes?
2. Frank had a way of ignoring clear outliers as seen at ~200klambda (vis plot)
3. How do I reduce over-fitting?

I'm happy to send my current fitting results of my complete sample if that would help.

Also I've been looking through the code and was hoping to get some clarification on the hyperparameter selection. How did you select the default values for alpha, p_0, and weights_smooth in the fit? And how would you approach altering these values for a better fit?

Cheers,
Brodie

**Comment by rbooth200** [comment]
Hi Brodie,

Without knowing more about your dataset its a bit difficult to diagnose exactly what is going on. It might be discussing these issues with Jeff, Marco, and I offline.

As you can see, by default, the prior in Frank (a Gaussian process) does not enforce the brightness be non-negative. We do have a way to generate non-negative profiles with frank (the solution objects produced by FrankFitter.fit() have a solve_non_negative method) but it is a bit delicate. I wouldn't advise using it until everything else is understood.

The best thing to do, if you really believe some of the visibility points are outliers, would be to remove them before fitting with frank - perhaps you could use e.g. a 5-sigma cut based on the fits you already have? However, the fit to the ATCA data looks really bad, which suggests there could be some other problem. In fact, I don't think I've seen a frank fit do quite that badly.

One important fact is that frank assumes that the weights are statistical (w ~ 1 / $\sigma^2$) and the noise is Gaussian. If the weights are too high, frank is going to try to fit every data point, too low and it won't fit any of the data at all. If the weights are not statistical can you estimate the variance of each visibility as a function of baseline and use that? We have a simple function in frank to do that, but it assumes the variance on each visibility is constant across the different baselines and requires the data to be deprojected first. We've only tested it on mock data from CASA simulations of ALMA observations so far (where the variance is constant, but unkown).

The paper is the best place to understand the how the hyper priors affect the fits is the data, it is currently under review. For now, I'd ignore p_0, as long as it is small then it doesn't affect the fit. (Too close to zero and you'll run into numerical problems. The default should be fine.) Increasing alpha (the range 1 to 1.5 or 2 is reasonable) will cause the code to avoid fitting low SNR data, which might be what you want.  Changing w_smooth generally only makes a small difference, (but larger w_smooth of 0.1 or 1 is probably recommended if you want to enforce non-negative fits).

Cheers,
Richard

**Comment by bjnorfolk** [comment]
Hi Richard,

Thanks for the reply, I'll email you with my response and further questions.

Cheers,
Brodie
