### ISSUE TITLE
Estimation of weights

### ISSUE THREAD

**Issue by rbooth200** [discsim/frank#98]
The functions for estimating the weights are wrong unless the weights passed in are 1 to start with. Also, we should probably include the imaginary part in estimating the weights

**Comment by rbooth200** [comment]
A function like this one:
```
def estimate_baseline_dependent_weight(q, V, bin_width):
  
    uvBin = UVDataBinner(q, V, np.ones_like(q), bin_width)
    var = 0.5*(uvBin.error.real**2 + uvBin.error.imag**2) * uvBin.bin_counts

    weights = np.full_like(q, np.nan)
    left, right = uvBin.bin_edges
    for i, [l,r] in enumerate(zip(left, right)):
        idx = (q >= l) & (q < r)
        weights[idx] = 1/var[i]

    assert np.all(~np.isnan(weights)), "Weights needed for all data points"
    return weights
```
Could be used to estimate the weights.

**Comment by jeffjennings** [comment]
Do you want to just replace `io.apply_correction_to_weights` with this?

**Comment by rbooth200** [comment]
Maybe, but I'm not totally convinced yet. I have a few questions:

- Should we add an option for computing a single estimate (e.g. the median) as well as a baseline dependent estimate?
- Should include the option of binning in log-space?
- Should we (optionally) use the information from existing weights in the estimation?

**Comment by jeffjennings** [comment]
> Maybe, but I'm not totally convinced yet. I have a few questions:
> 
> * Should we add an option for computing a single estimate (e.g. the median) as well as a baseline dependent estimate?

That's a good idea, could be useful for mock data, 
```
def estimate_baseline_dependent_weight(q, V, bin_width, point_estimate=False):
  
    uvBin = UVDataBinner(q, V, np.ones_like(q), bin_width)
    var = 0.5*(uvBin.error.real**2 + uvBin.error.imag**2) * uvBin.bin_counts

    weights = np.full_like(q, np.nan)
    left, right = uvBin.bin_edges
    for i, [l,r] in enumerate(zip(left, right)):
        idx = (q >= l) & (q < r)
        weights[idx] = 1/var[i]

    assert np.all(~np.isnan(weights)), "Weights needed for all data points"

    if point_estimate:
        return np.median(weights)

    return weights
```

> * Should include the option of binning in log-space?
I think this is also a good idea, we could just add the option in `UVDataBinner` and then the above code for `estimate_baseline_dependent_weight` need not changee.

> * Should we (optionally) use the information from existing weights in the estimation?
I would think if someone wants to fit for the weights, they don't trust the weights they have, and that those weights could be wrong in a number of ways, potentially biasing the result of `estimate_baseline_dependent_weight` in subtle ways. But maybe you're thinking of a use case I haven't realized.

**Comment by rbooth200** [comment]
> I would think if someone wants to fit for the weights, they don't trust the weights they have, and that those weights could be wrong in a number of ways, potentially biasing the result of estimate_baseline_dependent_weight in subtle ways. But maybe you're thinking of a use case I haven't realized.

The usage case would be for combining data sets with different telescopes (e.g. ALMA and ACA) where the telescopes have different sizes and therefore sensitivities. One would generally trust a baseline estimate from a larger telescope more - so it would be useful to be able to use the original weights in that case.

**Comment by jeffjennings** [comment]
ah ok. It seems like kind of an edge case in that either the weights aren't known or they come from CASA, but as in your email I appreciate there can be exceptions. Yeah if you want to make it adaptable for that, I could see more people using it than I'd initially expect.

**Comment by rbooth200** [comment]
I agree that for ALMA this is not necessary, but for other facilities (that might not use CASA in their data preparation) it may be more useful.

**Comment by rbooth200** [comment]
I'll prepare something soon.
